src/Entity/CardOrder.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\CardOrderRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CardOrderRepository::class)]
class CardOrder
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public private(set) int $id;

    #[ORM\Column(options: ['default' => 'CURRENT_TIMESTAMP'])]
    public private(set) readonly DateTimeImmutable $createdAt;

    #[ORM\Column]
    public private(set) bool $isPrintOrdered = false;

    #[ORM\Column(nullable: true)]
    #[Assert\Regex('/^[0-9A-F]{2}(:[0-9A-F]{2}){3}((:[0-9A-F]{2}){3})?$/')]
    #[Assert\NotBlank(allowNull: true)]
    public private(set) ?string $cardId = null;

    public function __construct(
        #[ORM\OneToOne(inversedBy: 'cardOrder')]
        #[ORM\JoinColumn(name: '`user`', nullable: false)]
        public private(set) readonly User $user,
    ) {
        $this->createdAt = new DateTimeImmutable();
    }

    public function setCardId(?string $cardId): static
    {
        if (is_string($cardId)) {
            $cardId = strtoupper($cardId);
        }

        $this->cardId = $cardId;

        return $this;
    }

    public function isReadyForPickUp(): bool
    {
        return is_string($this->cardId);
    }
}

src/Controller/ListCardOrdersController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\User;
use App\Repository\CardOrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

final class ListCardOrdersController extends AbstractController
{
    public function __construct(
        private readonly CardOrderRepository $repository,
    ) {
    }

    #[Route('/card_orders', name: 'list_card_orders')]
    #[IsGranted(User::ADMIN_ROLE)]
    public function index(): Response
    {
        $orders = $this->repository->findAll();

        return $this->render('list_card_orders/index.html.twig', [
            'orders' => $orders,
        ]);
    }
}

templates/list_card_orders/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ausweisanträge{% endblock %}

{% block body %}
    <h1>📋 Zu bearbeitende Anträge</h1>

    <table>
        <tr>
            <th>🧑 Name</th>
            <th>🖨️ Druck beauftragt?</th>
            <th>🪪 Ausweis-ID</th>
            <th>⏳ beantragt am</th>
            <th></th>
        </tr>
        {% for order in orders %}
            <tr>
                <td>{{ order.user.displayName }}</td>
                <td class="center">{{ order.isPrintOrdered ? '✅' : '❌' }}</td>
                <td class="center">
                    {% if order.cardId %}
                        <code>{{ order.cardId }}</code>
                    {% endif %}
                    {% if order.isPrintOrdered %}
                        <a href="{{ path('assign_card_id_to_order', {id: order.id}) }}">✏️</a>
                    {% endif %}
                </td>
                <td>{{ order.createdAt.format('Y-m-d H:i:s') }}</td>
                <td>
                    {% if order.readyForPickUp %}
                        <a href="{{ path('deliver_card_order', {id: order.id}) }}">🤝 Aushändigen</a>
                        <br>
                    {% endif %}
                    <a href="{{ path('delete_card_order', {id: order.id}) }}">🗑️ Löschen</a>
                </td>
            </tr>
        {% endfor %}
{#        TODO request printing -> csv export/mail + set print ordered #}
    </table>
{% endblock %}